services:
  server:
    build:
      dockerfile: "Dockerfile"
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app/server
    ports:
      - 3000:3000
  client:
    stdin_open: true
    env_file:
      - ./server/.env
    build:
      dockerfile: "Dockerfile"
      context: "./client"
    volumes:
      - /app/node_modules
      - ./client:/app/client
    ports:
      - 3001:3001