services:
  server:
    build:
      dockerfile: "./server/Dockerfile"
      context: "."
    volumes:
      - ./:/app/
    ports:
      - 3000:3000
    
  client:
    env_file:
      - ./server/.env
    build:
      dockerfile: "./Dockerfile"
      context: "."
    volumes:
      - ./src:/app/src
    ports:
      - 3001:3001
